import type { Metadata } from 'next'
import { Separator } from '@/components/ui/separator'
import Link from 'next/link'
import { ClientEnv } from '@/env/client'
import { BreadcrumbSchema } from '@/components/structured-data'
import { Section } from '@/components/ui/section'

export const dynamic = 'force-static'

const SITE_URL = ClientEnv.NEXT_PUBLIC_WEBSITE_URL
const META_TITLE = 'Risk Disclosure & Disclaimer'
const META_DESCRIPTION =
    'StockBrewAI is an educational stock-analysis tool, not a financial adviser. Read the full risk disclosure: AI reports are informational only, do not constitute investment advice, and investing carries risk of loss.'
const META_URL = `${SITE_URL}/disclaimer`

export const metadata: Metadata = {
    title: META_TITLE,
    description: META_DESCRIPTION,
    alternates: {
        canonical: META_URL,
    },
    openGraph: {
        title: META_TITLE,
        description: META_DESCRIPTION,
        url: META_URL,
    },
    twitter: {
        title: META_TITLE,
        description: META_DESCRIPTION,
    },
}

export default function DisclaimerPage() {
    return (
        <>
            <BreadcrumbSchema
                items={[
                    { name: 'Home', url: `${SITE_URL}/` },
                    { name: META_TITLE, url: META_URL },
                ]}
            />

            <main className="main-container">
                <div className="space-y-2">
                    <h1 className="text-2xl font-bold tracking-tight">
                        Risk Disclosure &amp; Disclaimer
                    </h1>
                    <p className="text-sm text-muted-foreground">Last updated: May 2026</p>
                </div>

                <Separator />

                <div className="space-y-7">
                    <Section title="1. No Financial Advice">
                        <p>
                            All reports, scores, summaries, and indicators produced by StockBrewAI
                            are generated by AI models from publicly available data and are provided
                            for{' '}
                            <strong className="text-foreground">
                                informational and educational purposes only
                            </strong>
                            . Nothing on this Service should be construed as:
                        </p>
                        <ul className="list-disc list-inside space-y-1 pl-1">
                            <li>
                                a recommendation, solicitation, or offer to buy, sell, or hold any
                                security, derivative, or financial instrument;
                            </li>
                            <li>
                                investment advice tailored to your personal financial situation,
                                objectives, time horizon, or risk profile;
                            </li>
                            <li>
                                tax, legal, accounting, or any other form of professional advice.
                            </li>
                        </ul>
                    </Section>

                    <Section title="2. Not a Regulated Adviser">
                        <p>
                            The Operator of StockBrewAI is not registered as an investment-services
                            provider with the Comissão do Mercado de Valores Mobiliários (CMVM) or
                            with any equivalent authority in another jurisdiction. We are not
                            authorised to provide personalised investment recommendations, manage
                            portfolios, or execute orders on your behalf.
                        </p>
                        <p>
                            Before acting on any information presented on this Service, you should
                            consult a licensed financial adviser, broker, or other qualified
                            professional who can assess your individual circumstances.
                        </p>
                    </Section>

                    <Section title="3. Investment Risk">
                        <p>
                            Investing in securities and other financial instruments involves
                            significant risk. The value of investments can rise and fall, and you
                            may lose some or all of the money you invest.{' '}
                            <strong className="text-foreground">
                                Past performance is not a reliable indicator of future results.
                            </strong>
                        </p>
                        <p>
                            Specific risks include but are not limited to: market volatility,
                            liquidity risk, credit risk, currency risk, regulatory changes, business
                            and operational risk specific to individual companies, and macroeconomic
                            shocks.
                        </p>
                    </Section>

                    <Section title="4. AI Output Limitations">
                        <p>
                            Reports are produced by large language models that process public
                            financial data. AI output:
                        </p>
                        <ul className="list-disc list-inside space-y-1 pl-1">
                            <li>
                                may contain errors, omissions, outdated information, or model
                                hallucinations;
                            </li>
                            <li>
                                reflects data available at the time of generation and may not
                                include the latest filings, news, or market events;
                            </li>
                            <li>
                                does not account for your personal context, holdings, tax situation,
                                or constraints;
                            </li>
                            <li>
                                should always be verified against original sources before any
                                decision is made.
                            </li>
                        </ul>
                        <p>
                            We make no warranty as to the accuracy, completeness, timeliness, or
                            suitability of any report or score.
                        </p>
                    </Section>

                    <Section title="5. Third-Party Data">
                        <p>
                            StockBrewAI relies on third-party data providers (including market-data
                            APIs and public filings) for the inputs to its analysis. We do not
                            independently verify this data and are not responsible for errors,
                            delays, or omissions in the data we receive.
                        </p>
                    </Section>

                    <Section title="6. Your Responsibility">
                        <p>
                            You are solely responsible for any investment decision you make. You
                            should:
                        </p>
                        <ul className="list-disc list-inside space-y-1 pl-1">
                            <li>conduct your own due diligence using multiple sources;</li>
                            <li>
                                consider your financial situation, investment objectives, and risk
                                tolerance;
                            </li>
                            <li>
                                consult a licensed professional before acting on any information
                                from this Service;
                            </li>
                            <li>only invest money you can afford to lose.</li>
                        </ul>
                    </Section>

                    <Section title="7. Jurisdictional Scope">
                        <p>
                            The Service is available globally but may not be appropriate or lawful
                            for use in every jurisdiction. It is your responsibility to ensure that
                            your use of the Service complies with the laws and regulations
                            applicable to you.
                        </p>
                    </Section>

                    <Section title="8. Contact">
                        <p>
                            For questions about this Risk Disclosure or about the limits of the
                            Service, contact us using the{' '}
                            <Link
                                href="/contact"
                                prefetch={false}
                                className="text-accent-blue underline underline-offset-2"
                            >
                                contact form
                            </Link>
                            .
                        </p>
                    </Section>
                </div>
            </main>
        </>
    )
}
