export enum PropmptsEnum {
    STOCK_ANALYSIS = 'STOCK_ANALYSIS',
    DEEP_FINANCIAL_BREAKDOWN = 'DEEP_FINANCIAL_BREAKDOWN',
    MOAT_ANALYSIS = 'MOAT_ANALYSIS',
    RISK_ANALYSIS = 'RISK_ANALYSIS',
    GROWTH_POTENTIAL_ANALYSIS = 'GROWTH_POTENTIAL_ANALYSIS',
}
