import type { EducationHubArticle } from '@/types/EducationHubArticle'

export const HOW_TO_ANALYZE_CASH_FLOW_ARTICLE: EducationHubArticle = {
    slug: 'how-to-analyze-cash-flow',
    title: 'How to Analyse Cash Flow: Why It Matters More Than Profit',
    description:
        'Profit is an opinion; cash is a fact. Learn what free cash flow reveals that the income statement hides — and the famous cases where the two told opposite stories.',
    publishedAt: '2025-05-01',
    readingTimeMinutes: 6,
    theme: 'stock-analysis',
    sections: [
        {
            body: '"Revenue is vanity, profit is sanity, cash flow is reality." The adage survives because it keeps being proven right: companies report healthy profits and run out of cash, and companies report losses while quietly generating mountains of it. Learning to read cash flow is the closest thing investing has to a lie detector for the income statement.',
        },
        {
            heading: 'The Three Cash Flow Statements',
            body: 'Every public company publishes three. Operating cash flow is the one that matters most: cash actually generated by the core business, collected revenue minus paid expenses, largely immune to accounting choices. Investing cash flow covers capital expenditure and acquisitions — what the company spends to maintain and grow. Financing cash flow tracks debt raised or repaid, dividends, and buybacks. Read them in that order, and operating cash flow first.',
        },
        {
            heading: 'Why Profit Can Be Misleading',
            body: 'Accounting profit uses accrual rules: revenue is booked when earned, not when the cash lands. A company that sells $10 million on credit in December records the revenue immediately, even if payment only arrives in March — or never. Non-cash charges like depreciation reduce reported profit without touching the bank balance. The result is that two companies can post identical net income while one is flush with cash and the other is quietly running on fumes. The income statement tells you a story; cash flow tells you whether it is true.',
        },
        {
            heading: 'When the Two Numbers Diverged — and It Mattered',
            body: 'The widening gap between reported profit and operating cash flow is one of the most reliable red flags in all of investing. Enron is the textbook case: it reported rising profits for years while its actual cash generation told a far bleaker story, masked by aggressive revenue recognition and off-balance-sheet vehicles. You do not need a fraud that extreme for the lesson to apply — any company whose net income keeps climbing while operating cash flow stalls or falls deserves hard questions about how those profits are being counted.',
        },
        {
            heading: 'Free Cash Flow: The Number That Is Hard to Fake',
            body: 'Free cash flow is operating cash flow minus capital expenditure — the cash left over after the business has paid to maintain and grow itself. It is what funds dividends, buybacks, debt reduction, and acquisitions, and it is far harder to manipulate than earnings. A useful gauge is free cash flow yield: FCF per share divided by the share price. A stock generating $5 of FCF per share at $100 has a 5% yield — a real cash return that does not depend on accounting assumptions. Mature, stable businesses with FCF yields above 5% are often attractive; fast growers frequently show low or negative yields because they are deliberately reinvesting every dollar.',
        },
        {
            heading: 'Red Flags to Watch',
            body: 'Three patterns deserve immediate suspicion. A persistent and widening gap between net income and operating cash flow can signal aggressive revenue recognition or mounting unpaid receivables. Capital expenditure rising fast without matching revenue growth suggests money being poured into projects that are not paying off. And a company sustaining its dividend by issuing debt — rather than from free cash flow — is funding generosity it cannot actually afford. Any one of these is a reason to dig deeper before the market does it for you.',
        },
    ],
}
