import Link from 'next/link'
import * as motion from 'motion/react-client'
import { ArrowRight } from 'lucide-react'
import { Button } from '@/components/ui/button'

const stats = [
    { value: '8', label: 'Report sections' },
    { value: '< 2min', label: 'Generation time' },
    { value: 'Free', label: 'First report' },
] as const

export function ReportHero() {
    return (
        <section className="main-container-lg border-b border-border">
            <div className="px-6 pb-24 lg:pb-32">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
                    <motion.div
                        initial={{ opacity: 0, y: 28 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
                    >
                        <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight leading-[1.05] max-w-2xl">
                            What does an AI analysis report look like?
                        </h1>
                        <p className="mt-6 text-lg text-muted-foreground leading-relaxed max-w-xl">
                            This is a real report generated by BrewStockAI. Professional-depth
                            analysis, available to anyone for less than a coffee.
                        </p>
                        <div className="mt-8 flex flex-wrap gap-3">
                            <Link href="/analysis" prefetch={false} className="contents">
                                <Button size="lg" className="gap-2 px-4 h-10 w-full sm:w-fit">
                                    Run your own analysis
                                    <ArrowRight className="size-4" />
                                </Button>
                            </Link>
                            <Link href="/pricing" prefetch={false} className="contents">
                                <Button
                                    size="lg"
                                    variant="outline"
                                    className="px-4 h-10 w-full sm:w-fit"
                                >
                                    See pricing
                                </Button>
                            </Link>
                        </div>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, x: 24 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.8, delay: 0.15, ease: [0.16, 1, 0.3, 1] }}
                        className="flex flex-col gap-5"
                    >
                        {stats.map((stat, i) => (
                            <motion.div
                                key={stat.label}
                                initial={{ opacity: 0, x: 16 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{
                                    duration: 0.6,
                                    delay: 0.2 + i * 0.1,
                                    ease: [0.16, 1, 0.3, 1],
                                }}
                                className="flex items-baseline gap-4 border-b border-border pb-5 last:border-0 last:pb-0"
                            >
                                <span className="text-5xl font-bold tracking-tight tabular-nums">
                                    {stat.value}
                                </span>
                                <span className="text-muted-foreground text-base">
                                    {stat.label}
                                </span>
                            </motion.div>
                        ))}
                    </motion.div>
                </div>
            </div>
        </section>
    )
}
